name: Mujtaba Mehdi
bio: I am a simple person with a love for technology
description: A blog about technology and stuff related
external-image: false
picture: assets/images/profile.jpg

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: auto


resume: true
resume-external: true
resume-url: 'https://docs.google.com/document/d/175XVp6ohWLxCKhwPVoDnbucmBtH2Usgp2rkzSl6F3F0/edit?usp=sharing'
url: 'https://mujjazi.github.io/'
permalink: '/:title/'
analytics-google: UA-68099646-2
linkedin: mujtabamehdi9
github: mujjazi
medium: 13besemmehdi
email: 13besemmehdi@seecs.edu.pk
authors:
  mujtaba:
    name: Mujtaba Mehdi
    bio: I love free and open source software
    external-image: false
    picture: assets/images/profile1.jpg
width: large
pagination:
  enabled: false
  sort_reverse: true
  title: ':title'
  per_page: 5
  permalink: '/:num/'
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
defaults:
  - scope:
      path: ''
      layout: post
    values:
      hidden: false
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2
jekyll-mentions:
  base_url: 'https://github.com'
compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  - travis.sh
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
  - node_modules
  - vendor
